image: python:latest

test:
  stage: test
  script:
    - pip install pip
    - python -V
    - python -m pip install --user tox
    - python -m tox


pages:
  stage: deploy
  image: ruby

  script:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generationr
  - gem install asciidoctor-pdf --pre
  - gem install wkhtmltox
  - python -V
  - asciidoctor-pdf text1.adoc -o documentation.pdf
  - asciidoctor text1.adoc -o index.html
  - mkdir .public
  - cp -r * .public
  - mv .public public

  environment:
    name: production
    url: 'https://stephx8x.gitlab.io/gl_tp3_gitlab'


  artifacts:
    paths:
    - public

  only:
  - master