image: python:latest

build:
  stage: build
  script:
    - pip install pip
    - python -V
    - python -m pip install --user tox
    - python -m to

pages:
  image: ruby
  script:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generationr
  - gem install asciidoctor-pdf --pre
  - gem install wkhtmltox
  - python -V
  - mkdir public
  - asciidoctor text1.adoc -o public/index.html
  - asciidoctor-pdf text1.adoc -o public/documentation.pdf
# rajoutez ici la génération du index.html ainsi que du fichier pdf
# dans un sous-répertoire que vous nommerez "public"

  artifacts:
    paths:
    - public

  only:
  - master